/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 desk_scene.glb --transform -t
Files: desk_scene.glb [31.59MB] > desk_scene-transformed.glb [3.86MB] (88%)
*/

import type * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

import FileQuery from 'queries/file'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder002: THREE.Mesh
    Circle: THREE.Mesh
    Buttons: THREE.Mesh
    Top: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Plane001_3: THREE.Mesh
    housing: THREE.Mesh
    housing_1: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube017: THREE.Mesh
    Cube017_1: THREE.Mesh
    Cube011: THREE.Mesh
    Cube015: THREE.Mesh
    Cube020: THREE.Mesh
    IOSHIELD: THREE.Mesh
    MOBOAORUSORANGETRANS: THREE.Mesh
    ['metal-mesh-500x500']: THREE.Mesh
    Cube027: THREE.Mesh
    Cube028: THREE.Mesh
    Cube045: THREE.Mesh
    ['rgb-hdd-cover-aorus-v1']: THREE.Mesh
    ['maxresdefault_(1)']: THREE.Mesh
    NVIDIA_LOGO: THREE.Mesh
    psuback: THREE.Mesh
    usb: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cylinder007: THREE.Mesh
    ['test-aorus-m2-souris-aorus-rgb2']: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cube057: THREE.Mesh
    Cube058: THREE.Mesh
    aorus_logotranspa: THREE.Mesh
    Cube075: THREE.Mesh
    Cube029: THREE.Mesh
    aorus_case_fans: THREE.Mesh
    Cube023: THREE.Mesh
  }
  materials: {
    PaletteMaterial003: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Buttons: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['mouse body.001']: THREE.MeshStandardMaterial
    ['put normal here.001']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    IOSHIELD: THREE.MeshStandardMaterial
    MOBOAORUSORANGETRANS: THREE.MeshStandardMaterial
    ['metal-mesh-500x500']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['rgb-hdd-cover-aorus-v1']: THREE.MeshStandardMaterial
    ['maxresdefault (1)']: THREE.MeshStandardMaterial
    ['NVIDIA LOGO']: THREE.MeshStandardMaterial
    psuback: THREE.MeshStandardMaterial
    usb: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['test-aorus-m2-souris-aorus-rgb2']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.059']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['aorus logotranspa']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
    ['aorus case fans']: THREE.MeshStandardMaterial
  }
}

export default function Model (props: JSX.IntrinsicElements['group']): JSX.Element {
  const { nodes, materials } = useGLTF(FileQuery('desk_scene.glb').publicURL) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.PaletteMaterial003} position={[-16.764, 31.933, -4.919]} rotation={[0, -Math.PI / 2, 0]} scale={[0.536, 1.897, 0.536]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[-16.764, 31.933, -4.919]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 1.795, 0.551]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.002']} position={[-16.764, 29.152, -4.919]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Buttons.geometry} material={materials.Buttons} />
      <mesh geometry={nodes.Top.geometry} material={materials['Material.003']} />
      <group position={[13.793, 29.328, 7.337]} rotation={[Math.PI, 0, Math.PI]} scale={[0.954, 0.997, 0.997]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['mouse body.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['put normal here.001']} />
      </group>
      <group position={[1.563, 30.26, 5.565]} rotation={[0, Math.PI / 2, 0]} scale={50}>
        <mesh geometry={nodes.housing.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.housing_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[16.481, 32.625, -5.514]} rotation={[0.461, -0.692, 0.307]} scale={3}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial008} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial006} />
      </group>
      <group position={[18.347, 33.947, -7.532]} rotation={[-1.574, 0.003, -0.746]} scale={3}>
        <mesh geometry={nodes.Cube017.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials.PaletteMaterial005} />
      </group>
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.010']} position={[31.693, 35.979, 1.682]} rotation={[0, -Math.PI / 2, 0]} scale={[8.674, 7.867, 4.499]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.016']} position={[36.049, 37.2, -2.294]} rotation={[0, Math.PI / 2, 0]} scale={[-4.469, 5.322, 0.035]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.020']} position={[32.177, 29.935, 1.173]} rotation={[0, -Math.PI / 2, 0]} scale={[8.034, 1.716, 3.697]} />
      <mesh geometry={nodes.IOSHIELD.geometry} material={materials.IOSHIELD} position={[35.132, 40.234, -7.006]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.324, 1.592, 1.543]} />
      <mesh geometry={nodes.MOBOAORUSORANGETRANS.geometry} material={materials.MOBOAORUSORANGETRANS} position={[35.203, 40.382, -5.801]} rotation={[0.92, 0, Math.PI / 2]} scale={0.317} />
      <mesh geometry={nodes['metal-mesh-500x500'].geometry} material={materials['metal-mesh-500x500']} position={[31.715, 43.843, 3.863]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[5, 5, 6.685]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.008']} position={[35.553, 39.542, 1.158]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.076, 2.214, 0.546]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Material.026']} position={[35.628, 39.542, 1.193]} rotation={[0, -Math.PI / 2, 0]} scale={[-0.053, 2.221, 0.487]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials['Material.027']} position={[28.918, 29.964, -4.629]} rotation={[0, -Math.PI / 2, 0]} scale={[1.774, 1.028, 0.258]} />
      <mesh geometry={nodes['rgb-hdd-cover-aorus-v1'].geometry} material={materials['rgb-hdd-cover-aorus-v1']} position={[28.447, 30.153, 1.305]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.847} />
      <mesh geometry={nodes['maxresdefault_(1)'].geometry} material={materials['maxresdefault (1)']} position={[31.773, 30.175, 10.364]} rotation={[Math.PI / 2, 0, 0]} scale={1.971} />
      <mesh geometry={nodes.NVIDIA_LOGO.geometry} material={materials['NVIDIA LOGO']} position={[28.46, 29.516, 6.008]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.259} />
      <mesh geometry={nodes.psuback.geometry} material={materials.psuback} position={[31.645, 29.893, -7.035]} rotation={[Math.PI / 2, 0, 0]} scale={2.974} />
      <mesh geometry={nodes.usb.geometry} material={materials.usb} position={[28.492, 43.852, 9.502]} scale={0.367} />
      <mesh geometry={nodes.Cube048.geometry} material={materials['Material.035']} position={[32.416, 39.406, -2.089]} rotation={[0, -Math.PI / 2, 0]} scale={[0.872, 2.004, 1.97]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials['Material.040']} position={[32.416, 39.406, -2.089]} rotation={[0, -Math.PI / 2, 0]} scale={[0.872, 2.004, 1.97]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.041']} position={[32.458, 39.427, -2.079]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.636, 1.711, 1.636]} />
      <mesh geometry={nodes['test-aorus-m2-souris-aorus-rgb2'].geometry} material={materials['test-aorus-m2-souris-aorus-rgb2']} position={[35.768, 33.532, 0.186]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={1.76} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.050']} position={[32.512, 35.225, -4.494]} rotation={[0, -Math.PI / 2, 0]} scale={[1.818, 0.529, 1.911]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.051']} position={[32.512, 35.225, -0.244]} rotation={[0, -Math.PI / 2, 0]} scale={[1.818, 0.529, 1.911]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials['Material.059']} position={[32.535, 35.998, -0.383]} rotation={[0, -Math.PI / 2, 0]} scale={[6.403, 0.633, 2.622]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials['Material.063']} position={[32.529, 36.68, -0.151]} rotation={[0, -Math.PI / 2, 0]} scale={[6.663, 0.04, 2.725]} />
      <mesh geometry={nodes.aorus_logotranspa.geometry} material={materials['aorus logotranspa']} position={[29.799, 35.079, -3.143]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.432, 0.454, 0.432]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials['Material.086']} position={[32.583, 35.77, -6.922]} rotation={[0, -Math.PI / 2, 0]} scale={[0.058, 0.887, 2.622]} />
      {/* @ts-expect-error this was generated by gltfjsx */}
      <instancedMesh args={[nodes.Cube029.geometry, materials.PaletteMaterial003, 5]} instanceMatrix={nodes.Cube029.instanceMatrix} />
      {/* @ts-expect-error this was generated by gltfjsx */}
      <instancedMesh args={[nodes.aorus_case_fans.geometry, materials['aorus case fans'], 10]} instanceMatrix={nodes.aorus_case_fans.instanceMatrix} />
      {/* @ts-expect-error this was generated by gltfjsx */}
      <instancedMesh args={[nodes.Cube023.geometry, materials.PaletteMaterial003, 8]} instanceMatrix={nodes.Cube023.instanceMatrix} />
    </group>
  )
}
