/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 desk_scene.glb --transform -t 
Files: desk_scene.glb [23.96MB] > desk_scene-transformed.glb [11.91MB] (50%)
*/

import React from 'react'
import type * as THREE from 'three'
import { useGLTF, useTexture } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

import Wood from 'images/ricardo/scene/wood.jpg'

type GLTFResult = GLTF & {
  nodes: {
    평면004: THREE.Mesh
    평면004_1: THREE.Mesh
    평면004_2: THREE.Mesh
    평면004_3: THREE.Mesh
    평면004_4: THREE.Mesh
    Top: THREE.Mesh
    Cylinder002: THREE.Mesh
    Circle: THREE.Mesh
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube017: THREE.Mesh
    Cube017_1: THREE.Mesh
    BezierCurve_1: THREE.Mesh
    BezierCurve_2: THREE.Mesh
    BezierCurve_3: THREE.Mesh
    BezierCurve_4: THREE.Mesh
    BezierCurve_5: THREE.Mesh
    BezierCurve_6: THREE.Mesh
    BezierCurve_7: THREE.Mesh
    BezierCurve_8: THREE.Mesh
    BezierCurve_9: THREE.Mesh
    BezierCurve_10: THREE.Mesh
    BezierCurve_11: THREE.Mesh
    BezierCurve_12: THREE.Mesh
    BezierCurve_13: THREE.Mesh
    BezierCurve_14: THREE.Mesh
    BezierCurve_15: THREE.Mesh
    BezierCurve_16: THREE.Mesh
    BezierCurve_17: THREE.Mesh
    BezierCurve_18: THREE.Mesh
    BezierCurve_19: THREE.Mesh
    BezierCurve_20: THREE.Mesh
    BezierCurve_21: THREE.Mesh
  }
  materials: {
    PaletteMaterial014: THREE.MeshStandardMaterial
    PaletteMaterial015: THREE.MeshStandardMaterial
    PaletteMaterial013: THREE.MeshStandardMaterial
    PaletteMaterial008: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial009: THREE.MeshPhysicalMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    GamerStorm_logo: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ROGTRANSPARENT: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.054']: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshStandardMaterial
    ['Material.071']: THREE.MeshStandardMaterial
    ['Material.067']: THREE.MeshStandardMaterial
    PaletteMaterial012: THREE.MeshPhysicalMaterial
    ['Material.095']: THREE.MeshStandardMaterial
  }
}

export default function Model (props: JSX.IntrinsicElements['group']): JSX.Element {
  const woodTexture = useTexture(Wood)
  const { nodes, materials } = useGLTF('/desk_scene.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-16.231, 31.498, 20.875]} rotation={[0.03, -Math.PI / 2, 0]} scale={20}>
        <mesh geometry={nodes.평면004.geometry} material={materials.PaletteMaterial014} />
        <mesh geometry={nodes.평면004_1.geometry} material={materials.PaletteMaterial015} />
        <mesh geometry={nodes.평면004_2.geometry} material={materials.PaletteMaterial013} />
        <mesh geometry={nodes.평면004_3.geometry} material={materials.PaletteMaterial008} />
        <mesh geometry={nodes.평면004_4.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.Top.geometry} material={materials.PaletteMaterial002}>
        <meshStandardMaterial map={woodTexture} />
      </mesh>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[-16.764, 31.933, -4.919]} rotation={[0, -Math.PI / 2, 0]} scale={[0.551, 1.795, 0.551]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.002']} position={[-16.764, 29.152, -4.919]} rotation={[0, -Math.PI / 2, 0]} />
      <group position={[16.184, 33.164, -8.442]} rotation={[0.314, -0.485, 0.151]} scale={4}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial005} />
      </group>
      <group position={[18.018, 34.657, -11.752]} rotation={[-1.638, 0.037, -0.505]} scale={4}>
        <mesh geometry={nodes.Cube017.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <group position={[33.415, 38.216, 2.059]} rotation={[Math.PI / 2, 1.571, 0]} scale={0.53}>
        <mesh geometry={nodes.BezierCurve_1.geometry} material={materials.PaletteMaterial009} />
        <mesh geometry={nodes.BezierCurve_2.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.BezierCurve_3.geometry} material={materials.GamerStorm_logo} />
        <mesh geometry={nodes.BezierCurve_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.BezierCurve_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.BezierCurve_6.geometry} material={materials.ROGTRANSPARENT} />
        <mesh geometry={nodes.BezierCurve_7.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.BezierCurve_8.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.BezierCurve_9.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.BezierCurve_10.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.BezierCurve_11.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.BezierCurve_12.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.BezierCurve_13.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.BezierCurve_14.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.BezierCurve_15.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.BezierCurve_16.geometry} material={materials.PaletteMaterial010} />
        <mesh geometry={nodes.BezierCurve_17.geometry} material={materials.PaletteMaterial011} />
        <mesh geometry={nodes.BezierCurve_18.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.BezierCurve_19.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.BezierCurve_20.geometry} material={materials.PaletteMaterial012} />
        <mesh geometry={nodes.BezierCurve_21.geometry} material={materials['Material.095']} />
      </group>
    </group>
  )
}

useGLTF.preload('/desk_scene.glb')
